// Initial seed data for BhoomiSetu AI National Land Acquisition System
// Firestore collections: users, projects, approvals, parcels, compensation, families, rr, milestones, notifications, documents, auditLogs

export const INITIAL_USER = {
  id: 'usr-001',
  name: 'Dr. Rajesh Kumar, IAS',
  role: 'ADMIN', // ADMIN | CENTRAL_MINISTRY | STATE_GOVT | DISTRICT_AUTHORITY | PROJECT_AGENCY | FIELD_OFFICER
  email: 'admin@bhoomisetu.gov.in',
  organization: 'National Land Authority, PMO',
  state: 'All India',
  district: 'All',
  phone: '+91 98765 43210'
};

export const DEMO_USERS = [
  {
    id: 'usr-001',
    name: 'Dr. Rajesh Kumar, IAS',
    role: 'ADMIN',
    email: 'admin@bhoomisetu.gov.in',
    organization: 'National Land Authority, PMO',
    state: 'All India',
    district: 'All'
  },
  {
    id: 'usr-002',
    name: 'Smt. V. Anitha, IAS',
    role: 'CENTRAL_MINISTRY',
    email: 'central.ministry@bhoomisetu.gov.in',
    organization: 'Ministry of Road Transport & Highways (MoRTH)',
    state: 'All India',
    district: 'All'
  },
  {
    id: 'usr-003',
    name: 'Thiru M. Selvam, IAS',
    role: 'STATE_GOVT',
    email: 'state.tn@bhoomisetu.gov.in',
    organization: 'Revenue & Disaster Management Dept, Govt of Tamil Nadu',
    state: 'Tamil Nadu',
    district: 'All'
  },
  {
    id: 'usr-004',
    name: 'Shri K. Sundaram, DRO',
    role: 'DISTRICT_AUTHORITY',
    email: 'dro.kanchipuram@bhoomisetu.gov.in',
    organization: 'District Land Acquisition Cell, Kanchipuram',
    state: 'Tamil Nadu',
    district: 'Kanchipuram'
  },
  {
    id: 'usr-005',
    name: 'Er. Suresh Verma',
    role: 'PROJECT_AGENCY',
    email: 'agency.nhai@bhoomisetu.gov.in',
    organization: 'National Highways Authority of India (NHAI)',
    state: 'Tamil Nadu',
    district: 'Kanchipuram'
  },
  {
    id: 'usr-006',
    name: 'Inspector P. Balaji',
    role: 'FIELD_OFFICER',
    email: 'field.officer@bhoomisetu.gov.in',
    organization: 'Sriperumbudur Land Revenue Survey Unit',
    state: 'Tamil Nadu',
    district: 'Kanchipuram'
  }
];

export const STATES_DISTRICTS = {
  'Tamil Nadu': ['Kanchipuram', 'Tiruvallur', 'Vellore', 'Coimbatore', 'Madurai'],
  'Karnataka': ['Bengaluru Urban', 'Bengaluru Rural', 'Ramanagara', 'Mysuru', 'Tumakuru'],
  'Maharashtra': ['Mumbai Suburban', 'Thane', 'Palghar', 'Pune', 'Nagpur'],
  'Gujarat': ['Ahmedabad', 'Surat', 'Vadodara', 'Kheda', 'Bharuch'],
  'Uttar Pradesh': ['Gautam Buddha Nagar', 'Ghaziabad', 'Agra', 'Varanasi', 'Lucknow']
};

export const INITIAL_PROJECTS = [
  {
    id: 'PRJ-2026-TN-001',
    name: 'Chennai–Bangalore Highway Expansion (NH-48)',
    type: 'Highway',
    ministry: 'Ministry of Road Transport and Highways',
    agency: 'National Highways Authority of India (NHAI)',
    state: 'Tamil Nadu',
    district: 'Kanchipuram',
    purpose: 'Widening of NH-48 from 4-lane to 8-lane corridor to ease industrial traffic between Sriperumbudur and Ranipet.',
    proposedLandArea: 500, // Acres
    acquiredLandArea: 365,
    estimatedCost: 500.0, // in Crores (₹500 Cr total project cost)
    compensationAssessed: 50.0, // ₹50 Cr
    compensationPaid: 38.0, // ₹38 Cr
    compensationPending: 12.0,
    startDate: '2025-04-01',
    completionDate: '2027-03-31',
    priority: 'HIGH',
    status: 'Acquisition in Progress', // Submitted | District Verification | State Clearance | Central Clearance | Acquisition in Progress | Completed | Rejected
    currentStage: 'Compensation Disbursement',
    healthScore: 78,
    affectedFamilies: 120,
    displacedFamilies: 35,
    rrCompletedPercentage: 68,
    legalDisputes: 8,
    approvalDelayDays: 18,
    aiRiskScore: 78, // % High risk
    aiRiskLevel: 'HIGH',
    bottleneckStage: 'Rehabilitation & Resettlement',
    bottleneckReason: '8 ongoing court disputes in Sriperumbudur taluk regarding compensation rate determination and pending R&R plot allocation.',
    description: 'Showcase National Expressway expansion project requiring fast-tracked land possession across 14 villages in Kanchipuram and Ranipet districts.',
    documentsCount: 24,
    parcelsCount: 42,
    createdDate: '2025-01-15',
    lastUpdated: '2026-09-07'
  },
  {
    id: 'PRJ-2026-MH-002',
    name: 'Mumbai–Ahmedabad High Speed Rail (Bullet Train Segment 4)',
    type: 'Railway',
    ministry: 'Ministry of Railways',
    agency: 'National High Speed Rail Corporation Ltd (NHSRCL)',
    state: 'Maharashtra',
    district: 'Palghar',
    purpose: 'Acquisition of linear land strip for elevated viaduct and maintenance depot.',
    proposedLandArea: 320,
    acquiredLandArea: 290,
    estimatedCost: 850.0,
    compensationAssessed: 120.0,
    compensationPaid: 115.0,
    compensationPending: 5.0,
    startDate: '2024-08-10',
    completionDate: '2026-12-31',
    priority: 'CRITICAL',
    status: 'Possession Pending',
    currentStage: 'Possession',
    healthScore: 89,
    affectedFamilies: 85,
    displacedFamilies: 20,
    rrCompletedPercentage: 92,
    legalDisputes: 2,
    approvalDelayDays: 5,
    aiRiskScore: 24,
    aiRiskLevel: 'LOW',
    bottleneckStage: 'Possession',
    bottleneckReason: 'Final boundary fencing pending clearance from Forest Department.',
    description: 'Bullet train track corridor passing through Palghar forest border.',
    documentsCount: 38,
    parcelsCount: 28,
    createdDate: '2024-06-01',
    lastUpdated: '2026-09-05'
  },
  {
    id: 'PRJ-2026-KA-003',
    name: 'Bengaluru Peripheral Ring Road Expressway',
    type: 'Urban Development',
    ministry: 'Ministry of Housing and Urban Affairs',
    agency: 'Bangalore Development Authority (BDA)',
    state: 'Karnataka',
    district: 'Bengaluru Urban',
    purpose: 'Construction of 73km 8-lane expressway around Bengaluru city.',
    proposedLandArea: 750,
    acquiredLandArea: 210,
    estimatedCost: 1200.0,
    compensationAssessed: 180.0,
    compensationPaid: 85.0,
    compensationPending: 95.0,
    startDate: '2025-02-15',
    completionDate: '2028-06-30',
    priority: 'HIGH',
    status: 'Compensation in Progress',
    currentStage: 'Compensation Assessment',
    healthScore: 42,
    affectedFamilies: 340,
    displacedFamilies: 110,
    rrCompletedPercentage: 25,
    legalDisputes: 24,
    approvalDelayDays: 45,
    aiRiskScore: 85,
    aiRiskLevel: 'HIGH',
    bottleneckStage: 'Compensation Disbursement',
    bottleneckReason: 'Disagreements on land valuation multiplier between farmers union and state treasury.',
    description: 'Ring road expansion to relieve heavy IT hub gridlock.',
    documentsCount: 19,
    parcelsCount: 65,
    createdDate: '2024-11-20',
    lastUpdated: '2026-09-08'
  },
  {
    id: 'PRJ-2026-GJ-004',
    name: 'Dholera Special Investment Region Renewable Energy Park',
    type: 'Renewable Energy',
    ministry: 'Ministry of New and Renewable Energy',
    agency: 'Gujarat Power Corporation Limited (GPCL)',
    state: 'Gujarat',
    district: 'Ahmedabad',
    purpose: '5,000 MW Solar & Wind Energy Park land acquisition.',
    proposedLandArea: 1200,
    acquiredLandArea: 1150,
    estimatedCost: 450.0,
    compensationAssessed: 35.0,
    compensationPaid: 35.0,
    compensationPending: 0.0,
    startDate: '2024-01-10',
    completionDate: '2026-10-31',
    priority: 'MEDIUM',
    status: 'Completed',
    currentStage: 'Project Completed',
    healthScore: 98,
    affectedFamilies: 15,
    displacedFamilies: 0,
    rrCompletedPercentage: 100,
    legalDisputes: 0,
    approvalDelayDays: 0,
    aiRiskScore: 12,
    aiRiskLevel: 'LOW',
    bottleneckStage: 'None',
    bottleneckReason: 'Project land possession successfully completed.',
    description: 'Mega solar park establishment on saline non-agricultural land.',
    documentsCount: 45,
    parcelsCount: 50,
    createdDate: '2023-12-01',
    lastUpdated: '2026-08-30'
  },
  {
    id: 'PRJ-2026-UP-005',
    name: 'Purvanchal Industrial Smart Node Corridor',
    type: 'Industrial Corridor',
    ministry: 'Ministry of Commerce and Industry',
    agency: 'UP Industrial Development Authority (UPIDA)',
    state: 'Uttar Pradesh',
    district: 'Gautam Buddha Nagar',
    purpose: 'Acquisition of 400 acres near Noida International Airport for semiconductor fabrication hub.',
    proposedLandArea: 400,
    acquiredLandArea: 180,
    estimatedCost: 650.0,
    compensationAssessed: 90.0,
    compensationPaid: 50.0,
    compensationPending: 40.0,
    startDate: '2025-06-01',
    completionDate: '2027-12-31',
    priority: 'HIGH',
    status: 'Submitted',
    currentStage: 'District Verification',
    healthScore: 64,
    affectedFamilies: 95,
    displacedFamilies: 18,
    rrCompletedPercentage: 40,
    legalDisputes: 5,
    approvalDelayDays: 14,
    aiRiskScore: 54,
    aiRiskLevel: 'MEDIUM',
    bottleneckStage: 'District Verification',
    bottleneckReason: 'Verification of joint ownership certificates in Jewar sub-division.',
    description: 'High-tech electronics manufacturing corridor expansion.',
    documentsCount: 14,
    parcelsCount: 30,
    createdDate: '2025-05-10',
    lastUpdated: '2026-09-06'
  }
];

export const INITIAL_APPROVALS = [
  {
    id: 'APP-TN-001',
    projectId: 'PRJ-2026-TN-001',
    projectName: 'Chennai–Bangalore Highway Expansion (NH-48)',
    stage: 'Submitted',
    approverRole: 'PROJECT_AGENCY',
    approverName: 'Er. Suresh Verma (NHAI)',
    status: 'Approved',
    remarks: 'Initial DPR & Gazette notification application submitted for 500 acres.',
    timestamp: '2025-01-16 10:30 AM'
  },
  {
    id: 'APP-TN-002',
    projectId: 'PRJ-2026-TN-001',
    projectName: 'Chennai–Bangalore Highway Expansion (NH-48)',
    stage: 'District Verification',
    approverRole: 'DISTRICT_AUTHORITY',
    approverName: 'Shri K. Sundaram (DRO Kanchipuram)',
    status: 'Approved',
    remarks: 'Cadastral land survey & revenue ownership verification completed for Sriperumbudur taluk.',
    timestamp: '2025-03-10 02:15 PM'
  },
  {
    id: 'APP-TN-003',
    projectId: 'PRJ-2026-TN-001',
    projectName: 'Chennai–Bangalore Highway Expansion (NH-48)',
    stage: 'State Clearance',
    approverRole: 'STATE_GOVT',
    approverName: 'Thiru M. Selvam, IAS (Govt of Tamil Nadu)',
    status: 'Approved',
    remarks: 'State Cabinet approved land acquisition sanction order & special R&R package.',
    timestamp: '2025-05-20 11:45 AM'
  },
  {
    id: 'APP-TN-004',
    projectId: 'PRJ-2026-TN-001',
    projectName: 'Chennai–Bangalore Highway Expansion (NH-48)',
    stage: 'Central Clearance',
    approverRole: 'CENTRAL_MINISTRY',
    approverName: 'Smt. V. Anitha, IAS (MoRTH)',
    status: 'Approved',
    remarks: 'Section 3A Gazette notification cleared by Central Ministry.',
    timestamp: '2025-07-02 04:00 PM'
  },
  {
    id: 'APP-UP-001',
    projectId: 'PRJ-2026-UP-005',
    projectName: 'Purvanchal Industrial Smart Node Corridor',
    stage: 'Submitted',
    approverRole: 'PROJECT_AGENCY',
    approverName: 'UPIDA Agency Director',
    status: 'Approved',
    remarks: 'Industrial node acquisition proposal filed.',
    timestamp: '2025-05-11 09:00 AM'
  },
  {
    id: 'APP-UP-002',
    projectId: 'PRJ-2026-UP-005',
    projectName: 'Purvanchal Industrial Smart Node Corridor',
    stage: 'District Verification',
    approverRole: 'DISTRICT_AUTHORITY',
    approverName: 'District Revenue Officer Jewar',
    status: 'Pending',
    remarks: 'Joint verification of agricultural land parcels in progress.',
    timestamp: '2025-06-01 02:30 PM'
  }
];

export const INITIAL_PARCELS = [
  {
    id: 'PAR-TN-KNC-001',
    projectId: 'PRJ-2026-TN-001',
    projectName: 'Chennai–Bangalore Highway Expansion (NH-48)',
    surveyNumber: '142/3A',
    state: 'Tamil Nadu',
    district: 'Kanchipuram',
    village: 'Sriperumbudur Rural',
    areaAcquired: 4.5, // Acres
    ownerCount: 3,
    ownerNames: 'M. Shanmugam, S. Velu, K. Lakshmi',
    acquisitionStatus: 'Compensation Pending',
    compensationStatus: 'Partially Paid',
    possessionStatus: 'Pending',
    lat: 12.9685,
    lng: 79.9412,
    disputeRisk: 'HIGH',
    marketValuePerAcre: 4500000,
    totalCompensation: 20250000,
    paidAmount: 10000000,
    pendingAmount: 10250000,
    fieldVerified: true,
    verificationDate: '2026-09-02',
    verifiedBy: 'Shri K. Sundaram (DRO)'
  },
  {
    id: 'PAR-TN-KNC-002',
    projectId: 'PRJ-2026-TN-001',
    projectName: 'Chennai–Bangalore Highway Expansion (NH-48)',
    surveyNumber: '148/1B',
    state: 'Tamil Nadu',
    district: 'Kanchipuram',
    village: 'Sunguvarchatram',
    areaAcquired: 8.2,
    ownerCount: 1,
    ownerNames: 'P. Ramanathan',
    acquisitionStatus: 'Acquired',
    compensationStatus: 'Fully Paid',
    possessionStatus: 'Possession Completed',
    lat: 12.9421,
    lng: 79.8732,
    disputeRisk: 'LOW',
    marketValuePerAcre: 4200000,
    totalCompensation: 34440000,
    paidAmount: 34440000,
    pendingAmount: 0,
    fieldVerified: true,
    verificationDate: '2026-08-28',
    verifiedBy: 'Shri K. Sundaram (DRO)'
  },
  {
    id: 'PAR-TN-KNC-003',
    projectId: 'PRJ-2026-TN-001',
    projectName: 'Chennai–Bangalore Highway Expansion (NH-48)',
    surveyNumber: '204/9C',
    state: 'Tamil Nadu',
    district: 'Kanchipuram',
    village: 'Mambakkam',
    areaAcquired: 12.0,
    ownerCount: 6,
    ownerNames: 'K. Parthiban & Brothers',
    acquisitionStatus: 'Disputed',
    compensationStatus: 'Disputed',
    possessionStatus: 'Pending',
    lat: 12.9215,
    lng: 79.8140,
    disputeRisk: 'HIGH',
    marketValuePerAcre: 5000000,
    totalCompensation: 60000000,
    paidAmount: 0,
    pendingAmount: 60000000,
    fieldVerified: false,
    verificationDate: null,
    verifiedBy: null
  },
  {
    id: 'PAR-TN-KNC-004',
    projectId: 'PRJ-2026-TN-001',
    projectName: 'Chennai–Bangalore Highway Expansion (NH-48)',
    surveyNumber: '89/4',
    state: 'Tamil Nadu',
    district: 'Kanchipuram',
    village: 'Molachur',
    areaAcquired: 3.8,
    ownerCount: 2,
    ownerNames: 'R. Govindan, G. Murali',
    acquisitionStatus: 'Under Verification',
    compensationStatus: 'Assessed',
    possessionStatus: 'Pending',
    lat: 12.9550,
    lng: 79.9100,
    disputeRisk: 'MEDIUM',
    marketValuePerAcre: 3800000,
    totalCompensation: 14440000,
    paidAmount: 0,
    pendingAmount: 14440000,
    fieldVerified: true,
    verificationDate: '2026-09-04',
    verifiedBy: 'Shri K. Sundaram (DRO)'
  },
  {
    id: 'PAR-MH-PAL-005',
    projectId: 'PRJ-2026-MH-002',
    projectName: 'Mumbai–Ahmedabad High Speed Rail (Bullet Train)',
    surveyNumber: '412/A',
    state: 'Maharashtra',
    district: 'Palghar',
    village: 'Manor',
    areaAcquired: 6.0,
    ownerCount: 2,
    ownerNames: 'Vijay Patil, Ramesh Patil',
    acquisitionStatus: 'Possession Completed',
    compensationStatus: 'Fully Paid',
    possessionStatus: 'Possession Completed',
    lat: 19.7210,
    lng: 72.9100,
    disputeRisk: 'LOW',
    marketValuePerAcre: 6000000,
    totalCompensation: 36000000,
    paidAmount: 36000000,
    pendingAmount: 0,
    fieldVerified: true,
    verificationDate: '2026-08-15',
    verifiedBy: 'District Collector Palghar'
  },
  {
    id: 'PAR-KA-BLR-006',
    projectId: 'PRJ-2026-KA-003',
    projectName: 'Bengaluru Peripheral Ring Road Expressway',
    surveyNumber: '77/12',
    state: 'Karnataka',
    district: 'Bengaluru Urban',
    village: 'Sarjapura',
    areaAcquired: 15.2,
    ownerCount: 8,
    ownerNames: 'H. Gowda Family Trust',
    acquisitionStatus: 'Disputed',
    compensationStatus: 'Disputed',
    possessionStatus: 'Pending',
    lat: 12.8600,
    lng: 77.7800,
    disputeRisk: 'HIGH',
    marketValuePerAcre: 12000000,
    totalCompensation: 182400000,
    paidAmount: 0,
    pendingAmount: 182400000,
    fieldVerified: false,
    verificationDate: null,
    verifiedBy: null
  }
];

export const INITIAL_COMPENSATION = [
  {
    id: 'CMP-TN-001',
    projectId: 'PRJ-2026-TN-001',
    parcelId: 'PAR-TN-KNC-001',
    surveyNumber: '142/3A',
    ownerName: 'M. Shanmugam',
    ownerAadhaar: 'XXXX-XXXX-4819',
    bankAccount: 'State Bank of India - SBIN0004812 (A/c *8921)',
    assessedAmount: 6750000,
    approvedAmount: 6750000,
    paidAmount: 3500000,
    pendingAmount: 3250000,
    paymentStatus: 'Partially Paid',
    disbursementDate: '2026-08-20',
    paymentMode: 'Aadhaar-seeded Direct Bank Transfer (DBT)',
    remarks: '1st tranche of ₹35 Lakh released. 2nd tranche pending sub-division clearance.'
  },
  {
    id: 'CMP-TN-002',
    projectId: 'PRJ-2026-TN-001',
    parcelId: 'PAR-TN-KNC-001',
    surveyNumber: '142/3A',
    ownerName: 'S. Velu',
    ownerAadhaar: 'XXXX-XXXX-9201',
    bankAccount: 'Indian Overseas Bank - IOBA0001044 (A/c *4412)',
    assessedAmount: 6750000,
    approvedAmount: 6750000,
    paidAmount: 6750000,
    pendingAmount: 0,
    paymentStatus: 'Paid',
    disbursementDate: '2026-08-22',
    paymentMode: 'Direct Bank Transfer (DBT)',
    remarks: 'Full compensation disbursed with 100% solatium.'
  },
  {
    id: 'CMP-TN-003',
    projectId: 'PRJ-2026-TN-001',
    parcelId: 'PAR-TN-KNC-002',
    surveyNumber: '148/1B',
    ownerName: 'P. Ramanathan',
    ownerAadhaar: 'XXXX-XXXX-1156',
    bankAccount: 'Canara Bank - CNRB0002105 (A/c *1029)',
    assessedAmount: 34440000,
    approvedAmount: 34440000,
    paidAmount: 34440000,
    pendingAmount: 0,
    paymentStatus: 'Paid',
    disbursementDate: '2026-08-28',
    paymentMode: 'Direct Bank Transfer (DBT)',
    remarks: 'Full payment completed. Possession handover certificate signed.'
  },
  {
    id: 'CMP-TN-004',
    projectId: 'PRJ-2026-TN-001',
    parcelId: 'PAR-TN-KNC-003',
    surveyNumber: '204/9C',
    ownerName: 'K. Parthiban',
    ownerAadhaar: 'XXXX-XXXX-6632',
    bankAccount: 'Axis Bank - UTIB0000841 (A/c *9011)',
    assessedAmount: 10000000,
    approvedAmount: 10000000,
    paidAmount: 0,
    pendingAmount: 10000000,
    paymentStatus: 'Disputed',
    disbursementDate: null,
    paymentMode: 'Pending Court Resolution',
    remarks: 'Compensation payment withheld due to High Court stay order on land valuation multiplier.'
  }
];

export const INITIAL_FAMILIES = [
  {
    id: 'FAM-001',
    projectId: 'PRJ-2026-TN-001',
    projectName: 'Chennai–Bangalore Highway Expansion (NH-48)',
    parcelId: 'PAR-TN-KNC-001',
    headOfFamily: 'M. Shanmugam',
    displacedStatus: 'Displaced',
    familyMembers: 5,
    compensationAwarded: 6750000,
    rrEntitlement: 'Housing Plot (1200 sqft) + ₹5 Lakh Resettlement Grant + Vocational Training',
    rrStatus: 'In Progress', // Not Started | Assessment | Approved | In Progress | Completed
    relocationStatus: 'Temporary Transit Shelter',
    housingAssistance: 'Allocated in Sriperumbudur Sector 4 R&R Colony',
    employmentAssistance: '1 Youth enrolled in NHAI Toll Operator Training',
    financialGrantPaid: 250000
  },
  {
    id: 'FAM-002',
    projectId: 'PRJ-2026-TN-001',
    projectName: 'Chennai–Bangalore Highway Expansion (NH-48)',
    parcelId: 'PAR-TN-KNC-001',
    headOfFamily: 'S. Velu',
    displacedStatus: 'Affected Only',
    familyMembers: 4,
    compensationAwarded: 6750000,
    rrEntitlement: 'Solatium 100% + Agricultural Equipment Subsidy',
    rrStatus: 'Completed',
    relocationStatus: 'Not Displaced (Partial Acquisition)',
    housingAssistance: 'N/A',
    employmentAssistance: 'Agricultural Rehabilitation Grant',
    financialGrantPaid: 6750000
  },
  {
    id: 'FAM-003',
    projectId: 'PRJ-2026-TN-001',
    projectName: 'Chennai–Bangalore Highway Expansion (NH-48)',
    parcelId: 'PAR-TN-KNC-003',
    headOfFamily: 'K. Parthiban',
    displacedStatus: 'Displaced',
    familyMembers: 7,
    compensationAwarded: 10000000,
    rrEntitlement: '2 BHK PUCCA House in Govt R&R Colony + ₹7.5 Lakh One-time annuity',
    rrStatus: 'Assessment',
    relocationStatus: 'Pending High Court Dispute Decision',
    housingAssistance: 'Pending Allotment',
    employmentAssistance: 'Under Assessment',
    financialGrantPaid: 0
  }
];

export const INITIAL_RR = [
  {
    id: 'RR-TN-001',
    projectId: 'PRJ-2026-TN-001',
    familyId: 'FAM-001',
    headOfFamily: 'M. Shanmugam',
    colonyLocation: 'Sriperumbudur Sector 4 R&R Smart Colony',
    plotAllotmentNo: 'Plot B-42 (1200 Sq Ft)',
    housingStatus: 'Under Construction',
    financialGrantTotal: 500000,
    financialGrantPaid: 250000,
    vocationalSkill: 'Solar PV Maintenance Technician',
    vocationalStatus: 'Enrolled',
    completionPercentage: 68,
    remarks: 'Housing foundation work completed. Financial grant tranche 1 paid.'
  },
  {
    id: 'RR-TN-002',
    projectId: 'PRJ-2026-TN-001',
    familyId: 'FAM-002',
    headOfFamily: 'S. Velu',
    colonyLocation: 'N/A (Retained Homestead)',
    plotAllotmentNo: 'N/A',
    housingStatus: 'Retained Self-Occupied',
    financialGrantTotal: 150000,
    financialGrantPaid: 150000,
    vocationalSkill: 'Drip Irrigation Equipment Management',
    vocationalStatus: 'Completed',
    completionPercentage: 100,
    remarks: 'Rehabilitation grant fully settled.'
  },
  {
    id: 'RR-TN-003',
    projectId: 'PRJ-2026-TN-001',
    familyId: 'FAM-003',
    headOfFamily: 'K. Parthiban',
    colonyLocation: 'Sriperumbudur Sector 4 R&R Smart Colony',
    plotAllotmentNo: 'Plot C-12 (Reserved)',
    housingStatus: 'Pending Allotment',
    financialGrantTotal: 750000,
    financialGrantPaid: 0,
    vocationalSkill: 'Heavy Vehicle Driving Certification',
    vocationalStatus: 'Pending',
    completionPercentage: 15,
    remarks: 'Awaiting court resolution on compensation before physical relocation.'
  }
];

export const INITIAL_MILESTONES = [
  {
    id: 'MLS-TN-001',
    projectId: 'PRJ-2026-TN-001',
    title: 'Section 3A Gazette Preliminary Notification',
    stageOrder: 1,
    targetDate: '2025-02-15',
    actualDate: '2025-02-10',
    status: 'Completed',
    overdueDays: 0,
    remarks: 'Gazette Notification published in Govt Gazette No. 412.'
  },
  {
    id: 'MLS-TN-002',
    projectId: 'PRJ-2026-TN-001',
    title: 'Joint Inspection & Cadastral Survey',
    stageOrder: 2,
    targetDate: '2025-04-30',
    actualDate: '2025-04-22',
    status: 'Completed',
    overdueDays: 0,
    remarks: 'Field boundary marking done across 14 villages.'
  },
  {
    id: 'MLS-TN-003',
    projectId: 'PRJ-2026-TN-001',
    title: 'Section 3G Compensation Award Declaration',
    stageOrder: 3,
    targetDate: '2025-08-01',
    actualDate: '2025-07-28',
    status: 'Completed',
    overdueDays: 0,
    remarks: 'Special DRO declared ₹50 Cr total compensation award.'
  },
  {
    id: 'MLS-TN-004',
    projectId: 'PRJ-2026-TN-001',
    title: 'Direct Bank Transfer (DBT) Compensation Disbursement',
    stageOrder: 4,
    targetDate: '2026-06-30',
    actualDate: null,
    status: 'Overdue',
    overdueDays: 71,
    remarks: '₹12 Cr compensation pending due to 8 disputed parcels in Sriperumbudur.'
  },
  {
    id: 'MLS-TN-005',
    projectId: 'PRJ-2026-TN-001',
    title: 'Physical Land Possession Handover',
    stageOrder: 5,
    targetDate: '2026-09-30',
    actualDate: null,
    status: 'In Progress',
    overdueDays: 0,
    remarks: '365 of 500 Acres taken physical possession.'
  },
  {
    id: 'MLS-TN-006',
    projectId: 'PRJ-2026-TN-001',
    title: 'R&R Housing Colony Handover & Relocation',
    stageOrder: 6,
    targetDate: '2026-11-15',
    actualDate: null,
    status: 'In Progress',
    overdueDays: 0,
    remarks: 'Sector 4 R&R colony construction at 68%.'
  },
  {
    id: 'MLS-TN-007',
    projectId: 'PRJ-2026-TN-001',
    title: 'Final Civil Project Construction & Completion',
    stageOrder: 7,
    targetDate: '2027-03-31',
    actualDate: null,
    status: 'Pending',
    overdueDays: 0,
    remarks: 'Scheduled for completion upon full corridor clearance.'
  }
];

export const INITIAL_DOCUMENTS = [
  {
    id: 'DOC-TN-001',
    projectId: 'PRJ-2026-TN-001',
    projectName: 'Chennai–Bangalore Highway Expansion (NH-48)',
    title: 'Section 3A Land Acquisition Gazette Notification',
    documentType: 'Gazette Notification',
    uploadedBy: 'NHAI Project Director',
    uploadDate: '2025-02-10',
    version: 'v1.2',
    status: 'VERIFIED',
    aiVerificationStatus: 'GREEN',
    aiNotes: 'Document appears valid. Official Govt Gazette stamp match 99.4%.',
    fileUrl: '#'
  },
  {
    id: 'DOC-TN-002',
    projectId: 'PRJ-2026-TN-001',
    projectName: 'Chennai–Bangalore Highway Expansion (NH-48)',
    title: 'Survey No 142/3A Patta & Chitta Ownership Extract',
    documentType: 'Land Records',
    uploadedBy: 'District Revenue Office',
    uploadDate: '2025-04-18',
    version: 'v1.0',
    status: 'NEEDS_ATTENTION',
    aiVerificationStatus: 'RED',
    aiNotes: 'Potential mismatch detected: Survey number on page 2 (142/3B) does not match main project parcel record (142/3A). Owner name spelling variance detected.',
    fileUrl: '#'
  },
  {
    id: 'DOC-TN-003',
    projectId: 'PRJ-2026-TN-001',
    projectName: 'Chennai–Bangalore Highway Expansion (NH-48)',
    title: 'Joint Inspection & Land Valuation Award Determination',
    documentType: 'Award Document',
    uploadedBy: 'Special Tahsildar LA',
    uploadDate: '2025-07-22',
    version: 'v2.0',
    status: 'VERIFIED',
    aiVerificationStatus: 'GREEN',
    aiNotes: 'Valid award determination certificate with revenue officer signature.',
    fileUrl: '#'
  }
];

export const INITIAL_NOTIFICATIONS = [
  {
    id: 'NTF-001',
    priority: 'CRITICAL', // LOW | MEDIUM | HIGH | CRITICAL
    title: 'HIGH DELAY RISK DETECTED',
    message: 'Chennai–Bangalore Highway Expansion predicted delay risk jumped to 78% due to 8 pending legal disputes in Sriperumbudur taluk.',
    projectId: 'PRJ-2026-TN-001',
    timestamp: '2026-09-08 10:30 AM',
    read: false,
    category: 'AI_RISK'
  },
  {
    id: 'NTF-002',
    priority: 'HIGH',
    title: 'Compensation Disbursement Overdue',
    message: '₹12.0 Crore compensation remains pending for over 60 days in Kanchipuram district.',
    projectId: 'PRJ-2026-TN-001',
    timestamp: '2026-09-07 04:15 PM',
    read: false,
    category: 'COMPENSATION'
  },
  {
    id: 'NTF-003',
    priority: 'MEDIUM',
    title: 'AI Document Verification Flagged Mismatch',
    message: 'Survey document DOC-TN-002 flagged red for survey number mismatch (142/3B vs 142/3A).',
    projectId: 'PRJ-2026-TN-001',
    timestamp: '2026-09-06 11:20 AM',
    read: true,
    category: 'DOCUMENT'
  },
  {
    id: 'NTF-004',
    priority: 'HIGH',
    title: 'District Approval Pending Review',
    message: 'Purvanchal Industrial Smart Node Corridor awaiting District Collector review in Gautam Buddha Nagar.',
    projectId: 'PRJ-2026-UP-005',
    timestamp: '2026-09-05 09:45 AM',
    read: false,
    category: 'APPROVAL'
  }
];

export const INITIAL_AUDIT_LOGS = [
  {
    id: 'AUD-901',
    timestamp: '2026-09-08 11:45:12',
    userName: 'Dr. Rajesh Kumar, IAS',
    userRole: 'ADMIN',
    action: 'AI_DELAY_PREDICTION_RUN',
    project: 'Chennai–Bangalore Highway Expansion',
    details: 'Triggered Random Forest predictive delay inference. Output: 78% HIGH RISK.',
    ipAddress: '10.24.8.102'
  },
  {
    id: 'AUD-902',
    timestamp: '2026-09-07 15:30:00',
    userName: 'Shri K. Sundaram, DRO',
    userRole: 'DISTRICT_AUTHORITY',
    action: 'FIELD_VERIFICATION_SUBMITTED',
    project: 'Chennai–Bangalore Highway Expansion',
    details: 'Verified parcel PAR-TN-KNC-001 via field mobile app with live GPS coordinates (12.9685, 79.9412).',
    ipAddress: '10.112.4.55'
  },
  {
    id: 'AUD-903',
    timestamp: '2026-09-06 09:15:24',
    userName: 'Er. Suresh Verma',
    userRole: 'PROJECT_AGENCY',
    action: 'PROPOSAL_SUBMITTED',
    project: 'Chennai–Bangalore Highway Expansion',
    details: 'Submitted revised acquisition proposal section 3A gazette documentation.',
    ipAddress: '10.50.2.14'
  }
];
